default_platform(:android)

platform :android do
  desc "Run command to automate build and distribute flutter apk"
  lane :firebase_distribution_builder do
      sh "flutter clean"
      sh "flutter pub get"
      sh "flutter build apk --release --no-tree-shake-icons"
      release = firebase_app_distribution(
            app: "1:437774384970:android:33ae1dd3767866eb358bb3",
            testers: "mestereslam20@gmail.com",
            android_artifact_path: "../build/app/outputs/apk/release/app-release.apk",
            android_artifact_type: "APK",
            release_notes: "Lots of amazing new features to test out!"
      )
  end
end
