name: IOS Firebase Distribution

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  distribute_ios:
    runs-on: macos-latest
    timeout-minutes: 60

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true
          cache-key: flutter-${{ runner.os }}-${{ hashFiles('**/pubspec.lock') }}

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "3.2.3"
          bundler-cache: true
          working-directory: ios

      # Fix CocoaPods installation issue
      - name: Reinstall CocoaPods
        run: |
          sudo gem uninstall cocoapods cocoapods-core cocoapods-downloader --ignore-dependencies --all || true
          sudo gem install cocoapods
          pod --version
        continue-on-error: true

      - name: Get Flutter dependencies
        run: flutter pub get

      - name: Build and Distribute iOS App
        env:
          FIREBASE_CLI_TOKEN: ${{ secrets.FIREBASE_CLI_TOKEN }}
        run: bundle exec fastlane ios ios_firebase_distribution_builder
        working-directory: ios

      - name: Clean up sensitive files
        if: always()
        run: |
          rm -f ios/firebase-service-account.json

      - name: Upload build artifacts
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: ios-build-logs
          path: |
            ios/fastlane/report.xml
            ios/build/fastlane/ipa/
            ios/fastlane/logs/
          retention-days: 7
